// Standalone, offline replay of every recorded game and search PV.
import {readFileSync,writeFileSync,readdirSync} from 'node:fs';
import {ROOT,START} from './arena_lib.mjs';
import {recordAt,moveLabel} from './record_helpers.mjs';
const D=process.env.V18_RESULTS||ROOT+'/results/v0.18',games=[];
for(const dir of ['matches'])for(const file of readdirSync(D+'/'+dir).filter(f=>f.endsWith('.json'))){
 const g=JSON.parse(readFileSync(D+'/'+dir+'/'+file));if(g.status!=='finished')throw Error('Unfinished game');
 const moves=dir==='matches'?g.moves:g.rows.map(r=>({...r,usi:r.move,variant:'yaneuraou',beforeSfen:r.sfen}));
 const states=[START],labels=[],detail=[],prefix=[];
 for(const usi of g.opening){const p=recordAt(START,prefix).position;labels.push(moveLabel(p,usi));prefix.push(usi);states.push(recordAt(START,prefix).position.sfen);detail.push(null);}
 for(const m of moves){
  const p=recordAt(START,prefix).position;labels.push(moveLabel(p,m.usi));
  const a=m.analysis,teacher=m.variant==='yaneuraou',pv=teacher?a.info?.pv||[]:a.has_result?a.pv:a.fallback_pv;
  const lines=[],pvlabels=[];let local=[];
  for(const u of pv){const q=recordAt(p.sfen,local).position;pvlabels.push(moveLabel(q,u));local.push(u);lines.push(recordAt(p.sfen,local).position.sfen);}
  let score=teacher?a.info?.score:a.has_result?a.score:a.fallback_partial_score;
  const type=teacher?a.info?.type:'raw90';
  if(type==='raw90'&&score!==null&&score!==undefined)score=Math.round(score*100/90);
  detail.push({engine:teacher?'やねうら王':g.name==='root'?'学習した根の読み順':'読みの再利用',score,type:teacher?type:'cp',ms:teacher?a.wallMs:a.elapsed_ms,complete:teacher?true:a.has_result,pv,lines,pvlabels,before:p.sfen});
  prefix.push(m.usi);states.push(recordAt(START,prefix).position.sfen);
 }
 const title=dir==='selfplay'?`教師自己対戦 ${g.id}（${g.split}）`:`${g.opening.length?'中飛車6手開始':'戦型指定なし'}・自作${g.candidateSide==='black'?'先手':'後手'}・${g.ms/1000}秒対2秒・${g.name==='root'?'学習読み順':'読みの再利用'}`;
 games.push({id:dir+'/'+g.id,title,states,labels,detail,result:g.result,total:prefix.length});
}
const summary=JSON.parse(readFileSync(D+'/summary.json'));
const html=`<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>将棋探索実験 v0.18</title><style>
*{box-sizing:border-box}body{margin:0;background:#f2f4f6;color:#182733;font:15px system-ui,sans-serif}main{max-width:1080px;margin:24px auto;padding:16px}h1{font-size:27px;margin:0 0 10px}p{line-height:1.8}section{background:white;border:1px solid #dce2e7;border-radius:14px;padding:20px;margin:18px 0}select{width:100%;font:inherit;padding:10px;border-radius:8px;border:1px solid #aeb9c3}.layout{display:grid;grid-template-columns:minmax(280px,440px) 1fr;gap:24px;margin-top:18px}#board{display:grid;grid-template-columns:repeat(9,1fr);background:#dfbd7c;border:2px solid #67552e;aspect-ratio:1}.cell{border:1px solid #a18753;display:grid;place-items:center;font-size:clamp(16px,2.7vw,29px);font-family:serif;font-weight:bold}.white{transform:rotate(180deg)}.red{color:#b62121}.hands{min-height:28px;margin:6px 0}.controls{display:flex;gap:7px;margin:12px 0;flex-wrap:wrap}button{background:#e8eff4;color:#243849;border:1px solid #c5d0d8;border-radius:7px;padding:8px 12px;cursor:pointer}button:hover,button.active{background:#154e65;color:white}input{width:100%}#moves{max-height:310px;overflow:auto;display:flex;flex-wrap:wrap;gap:4px}#moves button{font-size:13px}#meta{padding:12px;background:#f1f5f8;border-radius:9px;line-height:1.8}#pv{display:flex;gap:5px;flex-wrap:wrap;margin-top:10px}.muted{color:#62707b;font-size:13px}.scroll{overflow:auto}table{border-collapse:collapse;width:100%;font-size:13px}th,td{text-align:left;border-bottom:1px solid #dde4e8;padding:9px;white-space:nowrap}th{background:#eef3f6}summary{cursor:pointer;font-weight:bold}#status{font-weight:bold;color:#154e65}@media(max-width:720px){main{margin:0;padding:10px}.layout{grid-template-columns:1fr}section{padding:14px}.cell{font-size:25px}#moves{max-height:180px}}
</style><main><h1>将棋探索実験 v0.18</h1><p>平手から自作AIとやねうら王が対局した8局を収録。指し手・盤面・そのときの読み筋を確認できます。対戦相手は固定したやねうら王NNUE 6.03です。</p><section><select id="game" aria-label="対局を選択"></select><div class="layout"><div><div class="hands" id="whiteHand"></div><div id="board" aria-label="将棋盤"></div><div class="hands" id="blackHand"></div><div class="controls"><button id="first">最初</button><button id="prev">◀ 戻る</button><button id="play">再生</button><button id="next">進む ▶</button><button id="last">最後</button></div><input id="slider" type="range" min="0" aria-label="手数"><div id="status"></div></div><div><div id="meta"></div><p class="muted">評価はその手を選んだ側から見た値です。教師と自作の値を同一精度とは扱いません。下の読み筋を押すと、その予測盤面を表示します。</p><div id="pv"></div><h3>棋譜</h3><div id="moves"></div></div></div></section><section><h2>持ち時間と着手の比較</h2><p class="muted">教師が指した4つの進行から採った12局面。候補差は共通候補集合を教師の深さ12で採点した値で、小さいほど良好です。</p><div class="scroll"><table id="quality"></table></div></section><section><h2>対局結果</h2><p class="muted">全局、平手初期局面から自由に指しています。500cp欄は、相手の評価で500cp以上の不利が3回連続して観測された最初の自作手。確定した敗着ではありません。</p><div class="scroll"><table id="results"></table></div></section><p class="muted">このファイルは外部通信を行いません。全手順は保存済みの実験結果です。静止探索を含む最大到達手数は、すべての応手をその長さまで読んだ保証ではありません。</p></main><script>
const games=${JSON.stringify(games).replaceAll('<','\\u003c')},data=${JSON.stringify(summary).replaceAll('<','\\u003c')};
const $=id=>document.getElementById(id),glyph={P:'歩',L:'香',N:'桂',S:'銀',G:'金',B:'角',R:'飛',K:'玉','+P':'と','+L':'杏','+N':'圭','+S':'全','+B':'馬','+R':'龍'};let current=0,ply=0,timer=null;
function board(sfen){const [ranks,side,hands]=sfen.split(' ');$('board').replaceChildren();for(const row of ranks.split('/')){let promoted=false;for(const ch of row){if(ch==='+'){promoted=true;continue}if(/[1-9]/.test(ch)){for(let i=0;i<+ch;i++){const e=document.createElement('div');e.className='cell';$('board').append(e)}continue}const e=document.createElement('div');e.className='cell';const span=document.createElement('span');span.textContent=glyph[(promoted?'+':'')+ch.toUpperCase()];span.className=(ch===ch.toLowerCase()?'white ':'')+(promoted?'red':'');e.append(span);$('board').append(e);promoted=false}}const hand={b:[],w:[]};for(const m of hands.matchAll(/(\\d*)([PLNSGBRplnsgbr])/g)){const ch=m[2];hand[ch===ch.toUpperCase()?'b':'w'].push(glyph[ch.toUpperCase()]+(m[1]||'1'))}$('blackHand').textContent='先手の持駒：'+(hand.b.join(' ' )||'なし');$('whiteHand').textContent='後手の持駒：'+(hand.w.join(' ')||'なし')}
function render(){const g=games[current];$('slider').max=g.total;$('slider').value=ply;board(g.states[ply]);$('status').textContent=ply+' / '+g.total+'手'+(ply?'　'+g.labels[ply-1]:'');const d=ply?g.detail[ply-1]:null;$('pv').replaceChildren();$('meta').textContent=d?d.engine+' ／ '+Math.round(d.ms)+'ms ／ '+(d.complete?'探索結果':'初回反復未完了・暫定手')+' ／ 評価 '+(d.score==null?'不明':d.type==='mate'?'詰み '+d.score:d.score+'cp'):'開始局面・指定された開始手順';if(d){d.pv.forEach((m,i)=>{const b=document.createElement('button');b.textContent=(i+1)+'. '+d.pvlabels[i];b.onclick=()=>{board(d.lines[i]);$('status').textContent='予測：'+(ply-1+i+1)+'手目 '+d.pvlabels[i]};$('pv').append(b)})}for(const b of $('moves').children)b.classList.toggle('active',+b.dataset.ply===ply)}
function choose(){current=+$('game').value;ply=0;$('moves').replaceChildren();games[current].labels.forEach((m,i)=>{const b=document.createElement('button');b.textContent=(i+1)+' '+m;b.dataset.ply=i+1;b.onclick=()=>{ply=i+1;render()};$('moves').append(b)});render()}
games.forEach((g,i)=>{const o=document.createElement('option');o.value=i;o.textContent=g.title+'（'+g.total+'手）';$('game').append(o)});$('game').onchange=choose;$('first').onclick=()=>{ply=0;render()};$('last').onclick=()=>{ply=games[current].total;render()};$('prev').onclick=()=>{ply=Math.max(0,ply-1);render()};$('next').onclick=()=>{ply=Math.min(games[current].total,ply+1);render()};$('slider').oninput=()=>{ply=+$('slider').value;render()};$('play').onclick=()=>{if(timer){clearInterval(timer);timer=null;$('play').textContent='再生'}else{$('play').textContent='一時停止';timer=setInterval(()=>{if(ply<games[current].total){ply++;render()}else{$('play').click()}},1000)}};
function table(id,headers,rows){const t=$(id),head=document.createElement('tr');headers.forEach(v=>{const x=document.createElement('th');x.textContent=v;head.append(x)});t.append(head);rows.forEach(r=>{const tr=document.createElement('tr');r.forEach(v=>{const c=document.createElement('td');c.textContent=v;tr.append(c)});t.append(tr)})}const name={baseline:'従来の通常探索',adaptive:'従来の選択的探索',root:'学習した根の読み順',cache:'読みの再利用',guard:'駒取りの選別',both:'再利用＋選別'};table('quality',['方式','秒','平均候補差cp','PV手数','最大到達の平均','初回未完了'],data.quality.map(r=>[name[r.variant],r.ms/1000,r.meanGap?.toFixed(1),r.meanPV.toFixed(2),r.meanSelectiveDepth.toFixed(1),r.firstIterationFailures]));table('results',['方式','秒','開始','自作','総手数','結果','500cp開始'],data.games.map(r=>[name[r.variant],r.ourMs/1000,r.opening==='free'?'指定なし':'中飛車',r.side==='black'?'先手':'後手',r.totalPlies,r.outcome==='loss'?'負け':r.outcome==='win'?'勝ち':r.outcome==='draw'?'引分':'未決着',r.firstSustained500Ply??'未観測']));choose();
</script></html>`;
writeFileSync(ROOT+'/v0.18-review.html',html);console.log(JSON.stringify({games:games.length,bytes:Buffer.byteLength(html)}));
